const colors = {
  light: {
    text: "#0A1628",
    tint: "#E85D2F",
    background: "#F0F4F8",
    foreground: "#0A1628",
    card: "#FFFFFF",
    cardForeground: "#0A1628",
    primary: "#E85D2F",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#FFFFFF",
    muted: "#E2EAF4",
    mutedForeground: "#4A6A8A",
    accent: "#FFF0EB",
    accentForeground: "#E85D2F",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#C8D8E8",
    input: "#C8D8E8",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
    info: "#0EA5E9",
    infoForeground: "#FFFFFF",
  },
  dark: {
    text: "#F0F4F8",
    tint: "#E85D2F",
    background: "#0A1628",
    foreground: "#F0F4F8",
    card: "#152035",
    cardForeground: "#F0F4F8",
    primary: "#E85D2F",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#F0F4F8",
    muted: "#1E3A5F",
    mutedForeground: "#8CA0BC",
    accent: "#2A1A10",
    accentForeground: "#FF8C5A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A5F",
    input: "#1E3A5F",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#0A1628",
    info: "#38BDF8",
    infoForeground: "#0A1628",
  },
  radius: 10,
};

export default colors;
